/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background.vue')['default']
    EarthMapPanel: typeof import('./src/components/EarthMapPanel.vue')['default']
    FinanceNodeRenewalTable: typeof import('./src/components/FinanceNodeRenewalTable.vue')['default']
    FinanceValuePanel: typeof import('./src/components/FinanceValuePanel.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IpQualityPanel: typeof import('./src/components/IpQualityPanel.vue')['default']
    LoadChart: typeof import('./src/components/LoadChart.vue')['default']
    LoadingCover: typeof import('./src/components/LoadingCover.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    MarkdownRenderer: typeof import('./src/components/MarkdownRenderer.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NetworkQualityPanel: typeof import('./src/components/NetworkQualityPanel.vue')['default']
    NodeCard: typeof import('./src/components/NodeCard.vue')['default']
    NodeEarthGlobe: typeof import('./src/components/NodeEarthGlobe.vue')['default']
    NodeEarthRealisticGlobe: typeof import('./src/components/NodeEarthRealisticGlobe.vue')['default']
    NodeGeneralCards: typeof import('./src/components/NodeGeneralCards.vue')['default']
    NodeList: typeof import('./src/components/NodeList.vue')['default']
    NodeListNameCell: typeof import('./src/components/NodeListNameCell.vue')['default']
    PingChart: typeof import('./src/components/PingChart.vue')['default']
    PingLatencyBarStrip: typeof import('./src/components/PingLatencyBarStrip.vue')['default']
    PingTaskQualityCell: typeof import('./src/components/PingTaskQualityCell.vue')['default']
    Provider: typeof import('./src/components/Provider.vue')['default']
    ProviderBrandIcons: typeof import('./src/components/ProviderBrandIcons.vue')['default']
    ProviderValuePanel: typeof import('./src/components/ProviderValuePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrafficProgress: typeof import('./src/components/TrafficProgress.vue')['default']
  }
}
